# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

dist: trusty
sudo: true

r:
- oldrel
- release
- devel

env:
  - KERAS_BACKEND="tensorflow"

r_binary_packages: 
 - rstan
 - rstanarm
 - igraph
 - RCurl
 - dplyr
 - git2r
 - shiny
 - glue
 - magrittr
 - stringi
 - colorspace
 - assertthat
 - utf8
 - stringr
 - RColorBrewer
 - dichromat
 - munsell
 - labeling
 - R6
 - viridisLite
 - cli
 - crayon
 - pillar
 - rlang
 - digest
 - gtable
 - plyr
 - reshape2
 - scales
 - tibble
 - lazyeval
 - ggplot2
 - StanHeaders
 - inline
 - gridExtra
 - Rcpp
 - RcppEigen
 - BH

cache:
  packages: true
  directories:
    - $HOME/.keras
    - $HOME/.cache/pip


before_script:
  - python3 -m pip install --upgrade --ignore-installed --user travis pip setuptools wheel virtualenv
  - python3 -m pip install --upgrade --ignore-installed --user travis keras h5py pyyaml requests Pillow scipy theano
  - R -e 'tensorflow::install_tensorflow()'

before_install:
  - sudo apt-get -y install libnlopt-dev 
  - sudo apt-get -y install python3.6
   
after_success:
  - Rscript -e 'covr::codecov()'
